services:
    frontend:
        image: ghcr.io/quales/vatsim-radar/production-prebuilt:latest

    worker:
        image: ghcr.io/quales/vatsim-radar/production-prebuilt:latest

    navigraph:
        image: ghcr.io/quales/vatsim-radar/production-prebuilt:latest
