name: Publish

on:
  push:
    branches: [ next, next-test ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - uses: ./.github/actions/codecheck

  push:
    runs-on: ubuntu-latest
    needs:
      - check
    permissions:
      contents: read
      packages: write
    environment:
      name: next
      url: https://next.ivao-radar.com
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Add .env file
        run: echo "DATABASE_URL=mysql://root:localhost@db:3306/radar?schema=public" > .env
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/quales/vatsim-radar/next:latest
          context: .
          push: true
          file: .config/Dockerfile

  push-public:
    runs-on: ubuntu-latest
    needs:
      - check
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Add .env file
        run: cp .env.example .env
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/quales/vatsim-radar/next-prebuilt:latest
          context: .
          push: true
          file: .config/debug.Dockerfile

  github-release:
    name: Release tag to Github
    needs:
      - push-public
      - push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Get Tag Name
        id: tagName
        uses: beaconbrigade/package-json-version@v0.3
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: next
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tagName.outputs.version }}
          name: ${{ steps.release.outputs.title }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          prerelease: true
